import AUTH_API_LIST from '../helpers/apiListAuth';
import API_LIST from '../helpers/apiList';

export const CLIENTS_REQUEST: string[] = [
  AUTH_API_LIST.TRADER.AUTHENTICATE,
  AUTH_API_LIST.TRADER.REGISTER,
  API_LIST.PENDING_ORDERS.ADD,
  API_LIST.PENDING_ORDERS.REMOVE,
  API_LIST.POSITIONS.UPDATE_SL_TP,
  API_LIST.POSITIONS.UPDATE_TOPING_UP,
  AUTH_API_LIST.PERSONAL_DATA.CONFIRM,
  AUTH_API_LIST.TRADER.FORGOT_PASSWORD,
  AUTH_API_LIST.TRADER.PASSWORD_RECOVERY,
  AUTH_API_LIST.TRADER.CHANGE_PASSWORD,
  AUTH_API_LIST.PERSONAL_DATA.CONFIRM,
  API_LIST.POSITIONS.OPEN,
  API_LIST.POSITIONS.CLOSE,
  API_LIST.WITHWRAWAL.CREATE,
  API_LIST.WITHWRAWAL.CANCEL,
];